name: LigandMPNN
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - numpy=1.23.5
  - biopython=1.79
  - scipy=1.12.0
  - pytorch=2.5.1
  - ml-collections=1.0.0
  - dm-tree=0.1.9
  - pip
  - pip:
        - prody

